name: CD

on:
  push:
    branches: [master]

permissions:
  actions: read
  contents: read
  id-token: write

env:
  GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
  GITHUB_APP_INSTALLATION_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
  GITHUB_APP_PEM_FILE: ${{ secrets.GH_APP_PEM_FILE }}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  apply:
    name: Apply
    runs-on: ubuntu-latest
    environment: global
    needs: [ci]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::519848832156:role/gha-infrastructure
          aws-region: eu-north-1

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v33

      - name: Cache Nix Store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-primary-key: never

      - name: Initialize Terraform
        run: nix develop .#ci -c terraform -chdir=global init

      - name: Download Plan Artifact
        uses: actions/download-artifact@v5
        with:
          name: plan-${{ github.sha }}
          path: ./global

      - name: Apply Plan
        run: nix develop .#ci -c terraform -chdir=global apply -auto-approve ./plan
