name: CD

on:
  push:
    branches: [master]

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  apply:
    name: Apply Plan
    strategy:
      fail-fast: false
      matrix:
        environment: [bootstrap, organization]
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    needs: [ci]
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.environment }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::519848832156:role/gha-infrastructure-write
          aws-region: eu-north-1

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Initialize Terraform
        working-directory: ./environments/${{ matrix.environment }}
        run: nix develop .#ci -c terraform init -input=false -lock-timeout=1m -lockfile=readonly

      - name: Download Plan Artifact
        uses: actions/download-artifact@v5
        with:
          name: plan-${{ matrix.environment }}-${{ github.sha }}
          path: ./environments/${{ matrix.environment }}

      - name: Apply Plan
        working-directory: ./environments/${{ matrix.environment }}
        run: nix develop .#ci -c terraform apply -input=false -lock-timeout=1m -auto-approve ./plan
        env:
          GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
          GITHUB_APP_INSTALLATION_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
          GITHUB_APP_PEM_FILE: ${{ secrets.GH_APP_PEM_FILE }}
