name: CI

on:
  pull_request:
    branches: [master]
  merge_group:
    types: [checks_requested]
  workflow_call:

permissions:
  actions: read
  contents: read
  id-token: write

env:
  GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
  GITHUB_APP_INSTALLATION_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
  GITHUB_APP_PEM_FILE: ${{ secrets.GH_APP_PEM_FILE }}

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/_ci.yaml
    strategy:
      matrix:
        environment: [global, development]
    with:
      environment: ${{ matrix.environment }}
    secrets: inherit

  succeed:
    name: Succeed
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - run: "true"
