name: CI

on:
  pull_request:
    branches: [master]
  merge_group:
    types: [checks_requested]
  workflow_call:
  workflow_dispatch:

jobs:
  start:
    name: Start
    runs-on: ubuntu-latest
    outputs:
      start: ${{ steps.merge-queue-ci-skipper.outputs.skip-check == 'false' }}
    steps:
      - name: Check If Starting
        id: merge-queue-ci-skipper
        uses: cariad-tech/merge-queue-ci-skipper@main

  flake:
    name: Check Flake
    runs-on: ubuntu-latest
    needs: [start]
    if: needs.start.outputs.start == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Check
        run: nix flake check --impure --all-systems

      - name: Format
        run: nix fmt -- --ci

      - name: Test
        run: nix develop .# --impure --command devenv test

  succeed:
    name: Succeed
    runs-on: ubuntu-latest
    needs:
      - flake
    steps: [{ run: "true" }]
