on:
  # pull_request:
  #   branches: [master]
  push:
    branches: [master]

permissions:
  id-token: write

jobs:
  run_job_with_aws:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main # Or a specific version
        with:
          role-to-assume: arn:aws:iam::519848832156:role/gha-infrastructure
          aws-region: eu-north-1

      - name: Get caller identity
        run: |
          aws sts get-caller-identity
